name: Deploy StoryTime App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t storytime .

      - name: List Docker images
        run: docker images

      - name: Tag Docker image
        run: docker tag storytime:latest sunilbista7/storytime:latest

      - name: Push Docker image to Docker Hub
        run: docker push sunilbista7/storytime:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Pull Docker image on EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.26.94.233
          docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}' &&
          docker pull sunilbista7/storytime:latest &&
          docker stop storytime || true &&
          docker rm storytime || true &&
          docker run -d -p 80:80 --name storytime sunilbista7/storytime:latest"
